server:
  port: 9400
spring:
  application:
    name: qiao_center
  datasource:
    url: jdbc:mysql://47.101.188.136:3306/qiao?useUnicode=true&characterEncoding=utf8
    username: qiao
    password: qiao854064170+
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

eureka:
  instance:
    prefer-ip-address: true # 注册服务的时候使用服务的ip地址
  client:
    service-url:
      defaultZone: http://localhost:9500/eureka/

